"""
OrderFlow — PySpark Batch Analytics
=====================================
Reads:   data/orders.parquet          (generated by export_orders.py)
Writes:  data/analytics/
           hourly.parquet             — orders per hour (completed / failed breakdown)
           by_item.parquet            — failure rate + avg retries per item
           retry_dist.parquet         — retry count distribution
           proc_stats.parquet         — processing latency (avg / p50 / p95)

Run standalone:
    python analytics/spark_batch.py

Or call run() from within the FastAPI process after export_orders.export_to_parquet().
"""
import os
import sys

ROOT   = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

_JDK = os.path.join(os.path.expanduser("~"), "jdk21", "jdk-21.0.5+11")
_HADOOP = os.path.join(os.path.expanduser("~"), "hadoop")
if os.path.isdir(_JDK):
    os.environ.setdefault("JAVA_HOME", _JDK)
if os.path.isdir(_HADOOP):
    os.environ.setdefault("HADOOP_HOME", _HADOOP)
INPUT  = os.path.join(ROOT, "data", "orders.parquet")
OUTPUT = os.path.join(ROOT, "data", "analytics")


def run() -> dict:
    from pyspark.sql import SparkSession
    from pyspark.sql import functions as F

    spark = (
        SparkSession.builder
        .appName("OrderFlow-Batch")
        .config("spark.sql.shuffle.partitions", "4")
        .config("spark.driver.memory", "512m")
        .config("spark.ui.enabled", "false")
        .getOrCreate()
    )
    spark.sparkContext.setLogLevel("WARN")

    df = spark.read.parquet(INPUT)
    n  = df.count()
    df.cache()
    os.makedirs(OUTPUT, exist_ok=True)

    # ── 1. Hourly throughput ─────────────────────────────────────────────────
    hourly = (
        df
        .withColumn("hour", F.date_trunc("hour", F.col("created_at")))
        .groupBy("hour")
        .agg(
            F.count("*").alias("total"),
            F.sum(F.when(F.col("status") == "COMPLETED", 1).otherwise(0)).alias("completed"),
            F.sum(F.when(F.col("status").isin("FAILED", "DEAD"), 1).otherwise(0)).alias("failed"),
        )
        .orderBy("hour")
    )
    hourly.write.mode("overwrite").parquet(os.path.join(OUTPUT, "hourly.parquet"))

    # ── 2. Failure rate by item ───────────────────────────────────────────────
    by_item = (
        df
        .groupBy("item")
        .agg(
            F.count("*").alias("total"),
            F.sum(F.when(F.col("status") == "COMPLETED", 1).otherwise(0)).alias("completed"),
            F.sum(F.when(F.col("status").isin("FAILED", "DEAD"), 1).otherwise(0)).alias("failed"),
            F.round(F.avg("retry_count"), 2).alias("avg_retries"),
            F.round(F.avg("price"), 2).alias("avg_price"),
        )
        .withColumn(
            "failure_pct",
            F.round(F.col("failed") / F.col("total") * 100, 1),
        )
        .orderBy(F.col("failure_pct").desc())
    )
    by_item.write.mode("overwrite").parquet(os.path.join(OUTPUT, "by_item.parquet"))

    # ── 3. Retry distribution ─────────────────────────────────────────────────
    retry_dist = (
        df
        .groupBy("retry_count")
        .agg(F.count("*").alias("count"))
        .orderBy("retry_count")
    )
    retry_dist.write.mode("overwrite").parquet(os.path.join(OUTPUT, "retry_dist.parquet"))

    # ── 4. Processing latency (completed orders only) ────────────────────────
    completed = df.filter(
        (F.col("status") == "COMPLETED") & F.col("processed_at").isNotNull()
    ).withColumn(
        "proc_seconds",
        F.unix_timestamp("processed_at") - F.unix_timestamp("created_at"),
    )
    if completed.count() > 0:
        proc_stats = completed.agg(
            F.round(F.avg("proc_seconds"), 3).alias("avg_s"),
            F.min("proc_seconds").cast("double").alias("min_s"),
            F.max("proc_seconds").cast("double").alias("max_s"),
            F.round(F.expr("percentile(proc_seconds, 0.5)"), 3).alias("p50_s"),
            F.round(F.expr("percentile(proc_seconds, 0.95)"), 3).alias("p95_s"),
            F.count("*").alias("n"),
        )
        proc_stats.write.mode("overwrite").parquet(os.path.join(OUTPUT, "proc_stats.parquet"))

    spark.stop()
    return {"orders_processed": n}


if __name__ == "__main__":
    result = run()
    print(f"[spark_batch] complete - {result['orders_processed']} orders -> {OUTPUT}")
