// src/products.ts
export interface Product {
  id: string;
  slug: string;
  name: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviews: number;
  category: string;
  badge?: 'Sale' | 'New' | 'Best Seller' | 'Limited';
  tagline: string;
  description: string;
  features: string[];
  inStock: boolean;
}

export const PRODUCTS: Product[] = [
  {
    id: 'laptop',
    slug: 'laptop',
    name: 'Laptop',
    price: 1299.00,
    rating: 4.7,
    reviews: 2847,
    category: 'Computers',
    badge: 'Best Seller',
    tagline: 'Thin, light, and incredibly fast',
    description:
      'A powerhouse laptop built for professionals and creatives. Features the latest-gen processor, a stunning OLED display, and all-day battery life packed into an ultra-thin chassis.',
    features: [
      '14" 2.8K OLED display at 120 Hz',
      '12-core processor with AI acceleration',
      '32 GB LPDDR5 RAM, 1 TB NVMe SSD',
      '18-hour battery life (MIL-SPEC tested)',
      'Thunderbolt 4, USB-C, HDMI 2.1 ports',
    ],
    inStock: true,
  },
  {
    id: 'mechanical-keyboard',
    slug: 'mechanical-keyboard',
    name: 'Mechanical Keyboard',
    price: 149.00,
    originalPrice: 179.00,
    rating: 4.8,
    reviews: 5621,
    category: 'Peripherals',
    badge: 'Sale',
    tagline: 'Every keystroke, perfected',
    description:
      'A premium tenkeyless mechanical keyboard with hot-swappable switches, per-key RGB lighting, and an aircraft-grade aluminum frame. Designed for coders, writers, and competitive gamers.',
    features: [
      'Hot-swappable tactile or linear switches',
      'Per-key RGB with 16M color support',
      'Aircraft-grade aluminum top case',
      'USB-C detachable cable with braided sleeve',
      'N-key rollover, programmable via companion app',
    ],
    inStock: true,
  },
  {
    id: '4k-monitor',
    slug: '4k-monitor',
    name: '4K Monitor',
    price: 449.00,
    rating: 4.6,
    reviews: 1893,
    category: 'Displays',
    tagline: 'See everything, miss nothing',
    description:
      'A 27-inch 4K IPS panel with factory-calibrated color accuracy, HDR400 support, and ultra-thin bezels. Ideal for design work, video editing, and immersive gaming.',
    features: [
      '27" 4K UHD IPS panel, 144 Hz',
      'Delta E < 2 factory color calibration',
      'HDR400, 99% sRGB, 95% DCI-P3',
      'USB-C (65 W PD), HDMI 2.1, DisplayPort 1.4',
      'Height, tilt, swivel, and pivot adjustment',
    ],
    inStock: true,
  },
  {
    id: 'webcam',
    slug: 'webcam',
    name: 'Webcam',
    price: 89.00,
    originalPrice: 119.00,
    rating: 4.4,
    reviews: 3241,
    category: 'Peripherals',
    badge: 'Sale',
    tagline: 'Look your best on every call',
    description:
      'A 4K autofocus webcam with low-light correction and a built-in privacy shutter. Whether you\'re presenting to clients or streaming live, every detail comes through sharp.',
    features: [
      '4K / 30 fps or 1080p / 60 fps',
      'AI-powered autofocus and exposure correction',
      'Built-in dual omni-directional microphones',
      'Physical privacy shutter',
      'Universal clip mount, USB-A / USB-C cable included',
    ],
    inStock: true,
  },
  {
    id: 'usb-hub',
    slug: 'usb-hub',
    name: 'USB-C Hub',
    price: 59.00,
    rating: 4.5,
    reviews: 7823,
    category: 'Accessories',
    badge: 'Best Seller',
    tagline: 'One port, endless possibilities',
    description:
      'A compact 10-in-1 USB-C hub that turns a single laptop port into a full desktop setup. Supports 4K HDMI, 100 W passthrough charging, SD cards, and more.',
    features: [
      '4K HDMI + DisplayPort dual-display output',
      '100 W USB-C power delivery passthrough',
      '3 × USB-A 3.2 Gen 2 (10 Gbps)',
      'SD and microSD card reader',
      'Gigabit Ethernet adapter',
    ],
    inStock: true,
  },
  {
    id: 'ssd',
    slug: 'ssd',
    name: 'SSD',
    price: 119.00,
    originalPrice: 139.00,
    rating: 4.9,
    reviews: 12043,
    category: 'Storage',
    badge: 'Sale',
    tagline: 'Blazing-fast storage in your pocket',
    description:
      'A 2 TB portable NVMe SSD with sequential read speeds up to 2000 MB/s. Rugged aluminum shell, drop-tested, and fits in a shirt pocket.',
    features: [
      '2 TB NVMe, up to 2000 MB/s read',
      'USB 3.2 Gen 2×2 (USB-C)',
      'IP55 water and dust resistance',
      'Drop-tested to 3 meters',
      'Compatible with PS5, Xbox Series X, PC, Mac',
    ],
    inStock: true,
  },
  {
    id: 'ram',
    slug: 'ram',
    name: 'RAM Kit',
    price: 89.00,
    rating: 4.7,
    reviews: 6234,
    category: 'Components',
    tagline: 'Unleash your system\'s full potential',
    description:
      'A 32 GB (2×16 GB) DDR5 kit running at 6000 MT/s with low-profile heatspreaders. Plug-and-play XMP 3.0 — no BIOS tuning required.',
    features: [
      '32 GB DDR5 dual-channel kit (2×16 GB)',
      '6000 MT/s, CL36 latency',
      'One-click XMP 3.0 / EXPO profile',
      'Low-profile aluminum heatspreader',
      'Lifetime warranty with free tech support',
    ],
    inStock: true,
  },
  {
    id: 'gpu',
    slug: 'gpu',
    name: 'GPU',
    price: 799.00,
    rating: 4.8,
    reviews: 934,
    category: 'Components',
    badge: 'Limited',
    tagline: 'Next-generation graphics, today',
    description:
      'A flagship discrete GPU with 16 GB GDDR7 VRAM, ray tracing, and AI-powered upscaling. Handles 4K gaming, 3D rendering, and large-model inference with ease.',
    features: [
      '16 GB GDDR7 VRAM, 384-bit bus',
      'Hardware ray tracing (3rd gen)',
      'AI frame generation and upscaling',
      'Triple-fan vapor chamber cooling',
      '3× DisplayPort 1.4, 1× HDMI 2.1',
    ],
    inStock: true,
  },
  {
    id: 'headphones',
    slug: 'headphones',
    name: 'Headphones',
    price: 249.00,
    originalPrice: 299.00,
    rating: 4.6,
    reviews: 4521,
    category: 'Audio',
    badge: 'Sale',
    tagline: 'Hear everything, block out the rest',
    description:
      'Over-ear wireless headphones with industry-leading active noise cancellation, 36-hour battery, and a premium audio profile tuned by recording engineers.',
    features: [
      'Adaptive ANC with wind-noise reduction',
      '40 mm custom-tuned drivers',
      '36-hour battery, 5-min quick charge for 3 hours',
      'Multipoint Bluetooth 5.3 (connect 2 devices)',
      'Foldable for travel, USB-C charging',
    ],
    inStock: true,
  },
  {
    id: 'docking-station',
    slug: 'docking-station',
    name: 'Docking Station',
    price: 199.00,
    rating: 4.5,
    reviews: 2134,
    category: 'Accessories',
    tagline: 'Your desk, fully connected',
    description:
      'A triple-display Thunderbolt 4 docking station that transforms your laptop into a complete workstation in one plug. Powers your laptop while connecting up to three 4K monitors.',
    features: [
      'Thunderbolt 4 host port (96 W PD)',
      'Triple 4K monitor output (2× TB4 + HDMI)',
      '5× USB-A 3.2, 2× USB-C 3.2',
      '2.5 Gb Ethernet + 3.5 mm audio combo',
      'SD 4.0 UHS-II card slot',
    ],
    inStock: true,
  },
  {
    id: 'router',
    slug: 'router',
    name: 'Router',
    price: 179.00,
    rating: 4.7,
    reviews: 3876,
    category: 'Networking',
    tagline: 'Fast Wi-Fi in every corner',
    description:
      'A Wi-Fi 7 router with 6 GHz tri-band support, MLO, and an intelligent QoS engine that prioritises gaming, video calls, and streaming automatically.',
    features: [
      'Wi-Fi 7 (802.11be) tri-band, 9.3 Gbps combined',
      '6 GHz, 5 GHz, 2.4 GHz with MLO',
      '4× 2.5 GbE LAN + 1× 10 GbE WAN port',
      'WPA3-Enterprise security',
      'AI-driven QoS — no manual config',
    ],
    inStock: true,
  },
  {
    id: 'microphone',
    slug: 'microphone',
    name: 'Microphone',
    price: 139.00,
    originalPrice: 169.00,
    rating: 4.8,
    reviews: 2987,
    category: 'Audio',
    badge: 'Sale',
    tagline: 'Studio sound on your desk',
    description:
      'A USB condenser microphone with a large 34 mm capsule, cardioid and omnidirectional polar patterns, and a zero-latency headphone output. Podcasters and streamers love it.',
    features: [
      '34 mm condenser capsule, 24-bit / 96 kHz',
      'Switchable cardioid / omnidirectional pattern',
      'Real-time monitoring via 3.5 mm headphone jack',
      'Mute button with LED status indicator',
      'Boom-arm compatible threaded mount included',
    ],
    inStock: true,
  },
  {
    id: 'mouse',
    slug: 'mouse',
    name: 'Mouse',
    price: 69.00,
    rating: 4.7,
    reviews: 9234,
    category: 'Peripherals',
    badge: 'Best Seller',
    tagline: 'Precision that never misses',
    description:
      'A lightweight wireless gaming mouse with a 26,000 DPI optical sensor, 70-hour battery, and a symmetrical shape that fits all grip styles.',
    features: [
      '26,000 DPI optical sensor, 1000 Hz polling',
      '2.4 GHz wireless + Bluetooth 5.0',
      '70-hour battery life, USB-C charging',
      '58 g ultralight with honeycomb shell option',
      '6 programmable buttons, onboard memory',
    ],
    inStock: true,
  },
  {
    id: 'speaker',
    slug: 'speaker',
    name: 'Speaker',
    price: 199.00,
    rating: 4.5,
    reviews: 1654,
    category: 'Audio',
    tagline: 'Room-filling sound, desktop footprint',
    description:
      'A 2.1 desktop speaker system with a down-firing subwoofer, digital signal processing, and a clean look that complements any setup.',
    features: [
      '2.1 stereo with 60 W peak output',
      'Down-firing subwoofer with bass reflex port',
      'Optical, RCA, 3.5 mm, and USB-C inputs',
      'DSP room-correction via companion app',
      'Solid wood satellite enclosures',
    ],
    inStock: true,
  },
  {
    id: 'thunderbolt-hub',
    slug: 'thunderbolt-hub',
    name: 'Thunderbolt Hub',
    price: 179.00,
    rating: 4.6,
    reviews: 876,
    category: 'Accessories',
    badge: 'New',
    tagline: 'Full Thunderbolt 4 bandwidth for every device',
    description:
      'A certified Thunderbolt 4 hub with three downstream TB4 ports and one upstream host port. Full 40 Gbps on every port — no bandwidth sharing.',
    features: [
      '3× Thunderbolt 4 downstream (40 Gbps each)',
      '1× Thunderbolt 4 host, 98 W PD passthrough',
      '1× USB-A 3.2 Gen 2 (10 Gbps)',
      'Daisy-chain up to 6 devices',
      'Intel-certified, Mac and PC compatible',
    ],
    inStock: true,
  },
];

export const CATEGORIES = [
  'All',
  'Computers',
  'Peripherals',
  'Displays',
  'Audio',
  'Storage',
  'Components',
  'Accessories',
  'Networking',
];
